"""
Generate `plover_stenalgo`'s static key-name table from the adopted Starboard
layout (`starboard3h.json`), so the Plover system plugin has no runtime
dependency on the solver stack (OR-Tools, pandas, ...) -- it only ever imports
this generated, dependency-free module.

Positions are index-based (key 0..25), not string-based, so this keeps working
if `starboard3h.json` is re-optimized and a key's phoneme label changes -- only
its position in `keyIDinSyllabicPart`/`_reservedKeyDisplayNames` matters.

Run: python -m util.export_plover_system
Requires `starboard3h.json` (a committed input).
"""
from src.keyboard import Starboard

KEYBOARD_JSON = "starboard3h.json"
OUTPUT_PATH = "plover_stenalgo/plover_stenalgo/_generated_keys.py"

# Ground truth captured 2026-09-21 by sniffing raw Gemini PR packets directly
# (bypassing Plover) while pressing physical keys 0-25 in order -- see the
# Plover-integration plan/session notes. NOT the naive "natural steno order"
# guess this used to be: keys 0, 1, 2, and 10 turned out to be wired to
# Gemini's number-bar bits (#A, #B, #C, #1), not letters or star bits at all;
# only key 15 sends a real star bit (*4). This is harmless for `plover_stenalgo`
# specifically because it never wires NUMBER_KEY/NUMBERS -- Gemini's number-bar
# bits behave as perfectly ordinary chordable keys under a system that doesn't
# opt them into number-mode semantics.
GEMINI_PR_LABELS: tuple[str, ...] = (
    "#A", "#B",                                             # 0, 1: unused reserved
    "#C", "S2-", "T-", "K-", "P-", "W-", "H-", "R-",         # 2-9: onset (key 2 unusable as a letter)
    "#1",                                                    # 10: star mark (not actually a star bit)
    "A-", "O-", "-E", "-U",                                  # 11-14: nucleus
    "*4",                                                    # 15: hash mark (the one real star bit)
    "-F", "-R", "-P", "-B", "-L", "-G", "-T", "-S", "-D", "-Z",  # 16-25: coda
)


def main() -> None:
    starboard = Starboard.fromJSONFile(KEYBOARD_JSON)
    if starboard is None:
        raise RuntimeError(f"{KEYBOARD_JSON} not found; run dictionary.py once first to generate it.")

    names = starboard.keyDisplayNames()
    implicitHyphenKeys = tuple(
        names[i] for i in starboard.keyIDinSyllabicPart["nucleus"]
    ) + (names[10],)  # nucleus keys + star, mirroring English's A-/O-/-E/-U/*
    geminiKeymap = dict(zip(names, GEMINI_PR_LABELS))

    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(
            f'"""Generated by `python -m util.export_plover_system` from '
            f'{KEYBOARD_JSON} -- do not edit by hand."""\n\n'
        )
        f.write("KEYS: tuple[str, ...] = (\n")
        for name in names:
            f.write(f"    {name!r},\n")
        f.write(")\n\n")
        f.write(f"IMPLICIT_HYPHEN_KEYS: tuple[str, ...] = {implicitHyphenKeys!r}\n\n")
        f.write("GEMINI_PR_KEYMAP: dict[str, str] = {\n")
        for name in names:
            f.write(f"    {name!r}: {geminiKeymap[name]!r},\n")
        f.write("}\n")
    print(f"Wrote {OUTPUT_PATH} ({len(names)} keys).")


if __name__ == "__main__":
    main()
