"""
Vendor the decoder's stdlib-only modules into the Plover dictionary plugin, so `plover_stenalgo` decodes
expression outlines without the pipeline (no `src` package, no numpy, no OR-Tools).

Copies `src/<module>.py` to `plover_stenalgo/plover_stenalgo/_core/<module>.py`, rewriting `from src.x import`
to the package-relative `from .x import`. The copy is generated: edit `src/`, rerun this, commit both
(`src/test/plover_plugin_test.py` fails when the copy is stale).

Run: python -m util.export_plover_plugin
"""
from __future__ import annotations

import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SOURCE = REPO / "src"
TARGET = REPO / "plover_stenalgo" / "plover_stenalgo" / "_core"

# The closure of src.expressiondecoder / expressionranking / expressiondata (checked stdlib-only by the test).
MODULES = ("strokes", "expressionmodel", "keyconflicts", "elision", "expressiondecoder", "expressionranking",
           "expressiondata")

HEADER = "# Generated by `python -m util.export_plover_plugin` from src/{name}.py -- do not edit by hand.\n"


def vendored(name: str) -> str:
    text = (SOURCE / f"{name}.py").read_text(encoding="utf-8")
    text = re.sub(r"^(\s*)from src\.(\w+) import", r"\1from .\2 import", text, flags=re.M)
    return HEADER.format(name=name) + text


def generate() -> dict[Path, str]:
    files = {TARGET / f"{name}.py": vendored(name) for name in MODULES}
    files[TARGET / "__init__.py"] = "# Generated by `python -m util.export_plover_plugin` -- do not edit by hand.\n"
    return files


def main() -> None:
    TARGET.mkdir(parents=True, exist_ok=True)
    for path, text in generate().items():
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(REPO)}")


if __name__ == "__main__":
    main()
